// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiOso2QfxLJ-6jH8IKWEubSH3PEsrhfY0',
    appId: '1:426052725403:web:8ffbceeebd2e5c6a9c743e',
    messagingSenderId: '426052725403',
    projectId: 'orbital-bcbac',
    authDomain: 'orbital-bcbac.firebaseapp.com',
    storageBucket: 'orbital-bcbac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI11QzQDu6aJ48REPiDZSgH5IvOEHeJD8',
    appId: '1:426052725403:android:6dec5e3dee53ac889c743e',
    messagingSenderId: '426052725403',
    projectId: 'orbital-bcbac',
    storageBucket: 'orbital-bcbac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJMYq5AUtJrhxZMwzBL0Ou2eNytB0AoNU',
    appId: '1:426052725403:ios:48463fcfc9b4fc1c9c743e',
    messagingSenderId: '426052725403',
    projectId: 'orbital-bcbac',
    storageBucket: 'orbital-bcbac.appspot.com',
    iosClientId: '426052725403-18kgeh9qj8ctp26qv2nfr06fla0p17dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled2',
  );
}
